"""add_password_reset_tokens

Revision ID: 2fb933d641ff
Revises: 490bd5c165b9
Create Date: 2026-05-10 23:15:52.323090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb933d641ff'
down_revision: Union[str, Sequence[str], None] = '490bd5c165b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('reviewed_by', sa.String(length=36), nullable=True))
    op.add_column('applications', sa.Column('approved_by', sa.String(length=36), nullable=True))
    op.add_column('applications', sa.Column('reviewer_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('institution_name', sa.String(length=512), nullable=False))
    op.add_column('applications', sa.Column('registration_number', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('contact_full_name', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('contact_title', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('contact_email', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('contact_phone', sa.String(length=30), nullable=False))
    op.add_column('applications', sa.Column('proposed_capital', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('primary_products', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('target_districts', sa.String(length=512), nullable=False))
    op.add_column('applications', sa.Column('declaration_accepted', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('declaration_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('additional_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_applications_applicant_id', 'applications', ['applicant_id'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_foreign_key(None, 'applications', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'applications', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_applicant_id', table_name='applications')
    op.drop_column('applications', 'submitted_at')
    op.drop_column('applications', 'additional_notes')
    op.drop_column('applications', 'declaration_accepted_at')
    op.drop_column('applications', 'declaration_accepted')
    op.drop_column('applications', 'target_districts')
    op.drop_column('applications', 'primary_products')
    op.drop_column('applications', 'proposed_capital')
    op.drop_column('applications', 'contact_phone')
    op.drop_column('applications', 'contact_email')
    op.drop_column('applications', 'contact_title')
    op.drop_column('applications', 'contact_full_name')
    op.drop_column('applications', 'registration_number')
    op.drop_column('applications', 'institution_name')
    op.drop_column('applications', 'reviewer_notes')
    op.drop_column('applications', 'approved_by')
    op.drop_column('applications', 'reviewed_by')
    op.drop_column('applications', 'version')
    # ### end Alembic commands ###
