"""remove_institution_type_and_display_order_from_documents

Revision ID: 512213a200d9
Revises: 8c9bd9e2ef1c
Create Date: 2026-05-10 19:48:02.085547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512213a200d9'
down_revision: Union[str, Sequence[str], None] = '8c9bd9e2ef1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
