"""add_password_reset_tokens

Revision ID: 82b6f9ba9377
Revises: fbeebfbf0e42
Create Date: 2026-05-10 14:58:37.636854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b6f9ba9377'
down_revision: Union[str, Sequence[str], None] = 'fbeebfbf0e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('institution_name', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'institution_name')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
