"""add_password_reset_tokens

Revision ID: 8c9bd9e2ef1c
Revises: 1e3cca1a1d66
Create Date: 2026-05-10 19:47:48.715021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9bd9e2ef1c'
down_revision: Union[str, Sequence[str], None] = '1e3cca1a1d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_type_defs_display_order'), table_name='document_type_definitions')
    op.drop_index(op.f('ix_doc_type_defs_institution_type'), table_name='document_type_definitions')
    op.drop_column('document_type_definitions', 'display_order')
    op.drop_column('document_type_definitions', 'institution_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_type_definitions', sa.Column('institution_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('document_type_definitions', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_doc_type_defs_institution_type'), 'document_type_definitions', ['institution_type'], unique=False)
    op.create_index(op.f('ix_doc_type_defs_display_order'), 'document_type_definitions', ['display_order'], unique=False)
    # ### end Alembic commands ###
