"""add_documents_and_institution_type

Revision ID: fbeebfbf0e42
Revises: 98fcb075fa0f
Create Date: 2026-05-10 01:07:05.352777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbeebfbf0e42'
down_revision: Union[str, Sequence[str], None] = '98fcb075fa0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type_definitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('institution_type', sa.String(length=100), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_type_defs_display_order', 'document_type_definitions', ['display_order'], unique=False)
    op.create_index('ix_doc_type_defs_institution_type', 'document_type_definitions', ['institution_type'], unique=False)
    op.create_index('ix_doc_type_defs_is_active', 'document_type_definitions', ['is_active'], unique=False)
    op.create_table('application_document_requirements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('document_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('is_required_snapshot', sa.Boolean(), nullable=False),
    sa.Column('is_satisfied', sa.Boolean(), nullable=False),
    sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'document_type_id', name='uq_app_doc_requirement')
    )
    op.create_index('ix_app_doc_req_application_id', 'application_document_requirements', ['application_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('document_type_id', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('upload_round', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_size_bytes <= 5242880', name='ck_documents_max_5mb'),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_documents_positive_size'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index('ix_documents_app_type_latest', 'documents', ['application_id', 'document_type_id', 'is_latest'], unique=False)
    op.create_index('ix_documents_app_type_version', 'documents', ['application_id', 'document_type_id', 'version_number'], unique=False)
    op.create_index('ix_documents_application_id', 'documents', ['application_id'], unique=False)
    op.create_index('ix_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    institution_type_enum = sa.Enum('COMMERCIAL_BANK', 'MICROFINANCE', 'FOREX_BUREAU', 'PAYMENT_PROVIDER', name='institutiontype')
    institution_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('applications', sa.Column('institution_type', institution_type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'institution_type')
    institution_type_enum = sa.Enum('COMMERCIAL_BANK', 'MICROFINANCE', 'FOREX_BUREAU', 'PAYMENT_PROVIDER', name='institutiontype')
    institution_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_documents_uploaded_by', table_name='documents')
    op.drop_index('ix_documents_application_id', table_name='documents')
    op.drop_index('ix_documents_app_type_version', table_name='documents')
    op.drop_index('ix_documents_app_type_latest', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_app_doc_req_application_id', table_name='application_document_requirements')
    op.drop_table('application_document_requirements')
    op.drop_index('ix_doc_type_defs_is_active', table_name='document_type_definitions')
    op.drop_index('ix_doc_type_defs_institution_type', table_name='document_type_definitions')
    op.drop_index('ix_doc_type_defs_display_order', table_name='document_type_definitions')
    op.drop_table('document_type_definitions')
    # ### end Alembic commands ###
